version: "3.9"
services:
  application:
    image: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - database
  database:
    image: mcr.microsoft.com/azure-sql-edge